server:
  port: 8081

#项目服务
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

##网关配置
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000
  ribbon:
    eager-load:
      enabled: true

